from daibatiesClassifier.components.data_ingestion import DataIngestion
from daibatiesClassifier.components.data_transformation import DataTransformation
from daibatiesClassifier.components.training import DataTraining